### ISSUE TITLE
初始化时indicator无选中样式

### ISSUE THREAD

**Issue by mycold** [zhouteng0217/SimpleBanner#1]
![image](https://user-images.githubusercontent.com/14937950/66905013-a72b2180-f037-11e9-8b1c-8d0942bd696b.png)
这个we位置修改也无效

**Comment by zhouteng0217** [comment]
@mycold  是有这个问题，我更新了下库的版本和demo的代码，现在应该好了

**Comment by mycold** [comment]
样式2和3初始化时如何让左侧也显示出来呢，而不是滑动才显示

**Comment by zhouteng0217** [comment]
其实正常情况下，只使用单一样式，肯定都是好的，demo里面，为了演示方便，把所有样式都综合在一起了，切换的时候，没有处理好。我更新了下demo, 在setStyle时，重新绑定下数据，让每种样式的演示都回归初始状态，这样就没问题了。不涉及切换的话，就只需要bindData一次，然后设置好recyclerview的padding和item的padding，监听滚动事件之类的。
